name: Breadcrumbsportfollio-github-action-cicd

# Trigger the workflow when there is a push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the server

    steps:
    # Step 1: Checkout the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v1

    # Step 2: Configure AWS credentials using the secrets stored in GitHub
    # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be stored as secrets in your GitHub repo
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ap-south-1

    # Step 3: Sync the files from the repository to the S3 bucket
    # The `--exclude ".git/*"` option excludes Git-related files, and `--acl public-read` makes the files publicly accessible
    - name: Deploy static website to s3bucket
      run: |
        aws s3 sync . s3://portfollio-github-action-cicd --delete --exclude ".git/*" --acl public-read
        
    # Optional Step 4: Invalidate CloudFront cache to ensure the latest version of files is served
    # Only runs if a CloudFront Distribution ID is provided as a secret
    # - name: Invalidate CloudFront cache (optional)
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"
      # if: ${{ secrets.CLOUDFRONT_DIST_ID != '' }}  # Conditional step that runs only if CLOUDFRONT_DIST_ID is provided
